# YAML FILE 
brick_data:
  brick_size:
    width: 0.04
    height: 0.08
    length: 0.2

  # define how many layers of brick shall we do
  layers: 3

  # define how many bricks each layer will contain
  thikness: 4
  angle: 90  # degrees
  radious: 0.6


  # define dedicated pick place
  pick_place:
    size: 0.5
    position:
      x: -0.5
      y: 0
      z: 0.05


